# Generated by Django 3.1.2 on 2021-07-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20201005_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('content', models.TextField(blank=True)),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Current News',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
